services:
  tennisdb:
    container_name: tennisdb
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-tennis}
    ports:
      - "127.0.0.1:5435:5432"

  tennistestdb:
    container_name: tennistestdb
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: tennistest
    ports:
      - "127.0.0.1:5436:5432"

