// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID        uuid.UUID
	Winner    *uuid.UUID
	ServerID  uuid.UUID
	SetID     *uuid.UUID
	MatchID   *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Match struct {
	ID           uuid.UUID
	NumberOfSets sql.NullInt32
	UserID       uuid.UUID
	TeamOne      uuid.UUID
	TeamTwo      uuid.UUID
	Winner       uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Player struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Point struct {
	ID          uuid.UUID
	Value       sql.NullInt32
	TeamID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	GameID      *uuid.UUID
	PointsOrder sql.NullInt32
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Token      string
	ExpiryDate time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Set struct {
	ID        uuid.UUID
	MatchID   uuid.UUID
	Winner    *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	ID        uuid.UUID
	Name      sql.NullString
	UserID    uuid.UUID
	PlayerOne uuid.UUID
	PlayerTwo *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	PasswordHash   string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RefreshTokenID *uuid.UUID
}
