// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: players.query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPlayerById = `-- name: GetPlayerById :one
SELECT id, first_name, last_name, created_at, updated_at 
FROM players
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlayerById(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
