// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNewTeamWithOnePlayer(ctx context.Context, arg CreateNewTeamWithOnePlayerParams) (Team, error)
	CreateTeamWithTwoPlayers(ctx context.Context, arg CreateTeamWithTwoPlayersParams) (Team, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlayerById(ctx context.Context, id uuid.UUID) (Player, error)
	DeleteTeamById(ctx context.Context, id uuid.UUID) (Team, error)
	DeleteTokenByUserId(ctx context.Context, userID uuid.UUID) error
	DeleteUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetAllTeamsByUserId(ctx context.Context, userID uuid.UUID) ([]Team, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetPlayerById(ctx context.Context, id uuid.UUID) (Player, error)
	GetTeamById(ctx context.Context, id uuid.UUID) (Team, error)
	GetTokenByUserId(ctx context.Context, userID uuid.UUID) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdatePlayerById(ctx context.Context, arg UpdatePlayerByIdParams) (Player, error)
	UpdateTeamById(ctx context.Context, arg UpdateTeamByIdParams) (Team, error)
	UpdateTokenByUserId(ctx context.Context, arg UpdateTokenByUserIdParams) (RefreshToken, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
