// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	uuid "github.com/gofrs/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
